# Generated by Django 3.2.6 on 2021-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210825_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jobs_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='offers_created',
            field=models.IntegerField(default=0),
        ),
    ]
